services:

    twitter-x-simplificado-db:
        image: mysql
        ports:
        - "3306:3306"
        expose:
        - "3306"
        environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=twitter-x-simplificado
        - MYSQL_USER=root